### ISSUE TITLE
Build is failing - what to do?

### ISSUE THREAD

**Issue by cbroberg** [SKempin/reactjs-tmdb-app#5]
After running $: gulp watch

==== C stack trace ===============================

    0   node                                0x0000000100bce203 v8::base::debug::StackTrace::StackTrace() + 19
    1   node                                0x0000000100bcb389 V8_Fatal + 233
    2   node                                0x0000000100147afa v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute) + 330
    3   fse.node                            0x0000000102784bb1 fse::FSEvents::Initialize(v8::Local<v8::Object>) + 197
    4   node                                0x00000001009cf21f node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) + 854
    5   node                                0x000000010017c39a v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) + 378
    6   node                                0x00000001001e023c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 924
    7   node                                0x00000001001df679 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 281
    8   ???                                 0x000033a1d30063a7 0x0 + 56770122769319
    9   ???                                 0x000033a1d335049a 0x0 + 56770126218394
fish: 'sudo gulp watch' terminated by signal SIGILL (Illegal instruction)

**Comment by SKempin** [comment]
@cbroberg What versions of Node and NPM do you have installed?

**Comment by cbroberg** [comment]
NPM 4.1.2
Node 7.5.0

**Comment by SKempin** [comment]
Please try Node v6.9.5 LTS. This hasn't been tested on v7.5.

**Comment by SKempin** [comment]
@cbroberg Any luck with this?

**Comment by cbroberg** [comment]
@SKempin Yes finally got it running by downgrading to LTS of NPM. Thanks for de advice. Still no clue on the search field bug with Safari on Mac and iPhone though
