### ISSUE TITLE
Background image returns 'null'

### ISSUE THREAD

**Issue by meendoo** [SKempin/reactjs-tmdb-app#8]
I noticed that there isn't a fallback image for the background.
The response for that comes as `https://image.tmdb.org/t/p/originalnull`

To test that I've typed in the movie title _Killer: A Journal of Murder_ (an excellent movie, btw)

Congrats with the project. Looks pretty neat.

**Comment by DanWilkes02** [comment]
What do you suggest? I've cloned the repo, but I can't see anything looking better than the black screen it does show.

**Comment by SKempin** [comment]
@DanWilkes02 Agreed, this is why I haven't created a fallback image for the background. However it would be nice to have a fallback for the poster image.

**Comment by DanWilkes02** [comment]
I might have a look at it now if your want see what i can do

**Comment by DanWilkes02** [comment]
I'm done, I'll send over a pull request from my fork in a sec

**Comment by meendoo** [comment]
I thought of a texture ([example](https://www.motto.net.ua/pic/201209/1366x768/motto.net.ua-9965.jpg)) applied to the background. In my opinion that works better than a request that fails.

**Comment by DanWilkes02** [comment]
@meendoo I did consider that but I thought that it might be confusing to a user. It might look like it hasn't loaded instead of there not being an image. I don't know though, it may be a better solution. @SKempin should probably decide what he thinks would work better

**Comment by SKempin** [comment]
Yes I think it may be confusing. If a background issue is to be used, it would need to denote that no artwork is available.
